version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types: [minor, patch]
        exclude-patterns:
          - google.golang.org/grpc
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types: [minor, patch]
  - package-ecosystem: docker
    directory: /build/package
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types: [minor, patch]
