// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v6.33.4
// source: src/node/rpc/protocol/node.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_CREATE                Operation = 1
	Operation_RECLAIM               Operation = 2
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "CREATE",
		2: "RECLAIM",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"CREATE":                1,
		"RECLAIM":               2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_src_node_rpc_protocol_node_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_src_node_rpc_protocol_node_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_src_node_rpc_protocol_node_proto_rawDescGZIP(), []int{0}
}

type EffectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorUid   string                 `protobuf:"bytes,1,opt,name=executor_uid,json=executorUid,proto3" json:"executor_uid,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	VolumeName    string                 `protobuf:"bytes,3,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	VolumeUid     string                 `protobuf:"bytes,4,opt,name=volume_uid,json=volumeUid,proto3" json:"volume_uid,omitempty"`
	OperationId   string                 `protobuf:"bytes,5,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EffectRequest) Reset() {
	*x = EffectRequest{}
	mi := &file_src_node_rpc_protocol_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EffectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EffectRequest) ProtoMessage() {}

func (x *EffectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_node_rpc_protocol_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EffectRequest.ProtoReflect.Descriptor instead.
func (*EffectRequest) Descriptor() ([]byte, []int) {
	return file_src_node_rpc_protocol_node_proto_rawDescGZIP(), []int{0}
}

func (x *EffectRequest) GetExecutorUid() string {
	if x != nil {
		return x.ExecutorUid
	}
	return ""
}

func (x *EffectRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EffectRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *EffectRequest) GetVolumeUid() string {
	if x != nil {
		return x.VolumeUid
	}
	return ""
}

func (x *EffectRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type CapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutorUid   string                 `protobuf:"bytes,1,opt,name=executor_uid,json=executorUid,proto3" json:"executor_uid,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PoolName      string                 `protobuf:"bytes,3,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	PoolUid       string                 `protobuf:"bytes,4,opt,name=pool_uid,json=poolUid,proto3" json:"pool_uid,omitempty"`
	Evidence      string                 `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Nonce         string                 `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityRequest) Reset() {
	*x = CapacityRequest{}
	mi := &file_src_node_rpc_protocol_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityRequest) ProtoMessage() {}

func (x *CapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_node_rpc_protocol_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityRequest.ProtoReflect.Descriptor instead.
func (*CapacityRequest) Descriptor() ([]byte, []int) {
	return file_src_node_rpc_protocol_node_proto_rawDescGZIP(), []int{1}
}

func (x *CapacityRequest) GetExecutorUid() string {
	if x != nil {
		return x.ExecutorUid
	}
	return ""
}

func (x *CapacityRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CapacityRequest) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *CapacityRequest) GetPoolUid() string {
	if x != nil {
		return x.PoolUid
	}
	return ""
}

func (x *CapacityRequest) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *CapacityRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type CapacityResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExecutorUid     string                 `protobuf:"bytes,1,opt,name=executor_uid,json=executorUid,proto3" json:"executor_uid,omitempty"`
	Evidence        string                 `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Nonce           string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TotalBytes      int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	AvailableBytes  int64                  `protobuf:"varint,5,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	AvailableInodes int64                  `protobuf:"varint,6,opt,name=available_inodes,json=availableInodes,proto3" json:"available_inodes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapacityResponse) Reset() {
	*x = CapacityResponse{}
	mi := &file_src_node_rpc_protocol_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityResponse) ProtoMessage() {}

func (x *CapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_node_rpc_protocol_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityResponse.ProtoReflect.Descriptor instead.
func (*CapacityResponse) Descriptor() ([]byte, []int) {
	return file_src_node_rpc_protocol_node_proto_rawDescGZIP(), []int{2}
}

func (x *CapacityResponse) GetExecutorUid() string {
	if x != nil {
		return x.ExecutorUid
	}
	return ""
}

func (x *CapacityResponse) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *CapacityResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *CapacityResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *CapacityResponse) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *CapacityResponse) GetAvailableInodes() int64 {
	if x != nil {
		return x.AvailableInodes
	}
	return 0
}

var File_src_node_rpc_protocol_node_proto protoreflect.FileDescriptor

const file_src_node_rpc_protocol_node_proto_rawDesc = "" +
	"\n" +
	" src/node/rpc/protocol/node.proto\x12\x0fshiftpv.node.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xb2\x01\n" +
	"\rEffectRequest\x12!\n" +
	"\fexecutor_uid\x18\x01 \x01(\tR\vexecutorUid\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1f\n" +
	"\vvolume_name\x18\x03 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"volume_uid\x18\x04 \x01(\tR\tvolumeUid\x12!\n" +
	"\foperation_id\x18\x05 \x01(\tR\voperationId\"\xbb\x01\n" +
	"\x0fCapacityRequest\x12!\n" +
	"\fexecutor_uid\x18\x01 \x01(\tR\vexecutorUid\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1b\n" +
	"\tpool_name\x18\x03 \x01(\tR\bpoolName\x12\x19\n" +
	"\bpool_uid\x18\x04 \x01(\tR\apoolUid\x12\x1a\n" +
	"\bevidence\x18\x05 \x01(\tR\bevidence\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\tR\x05nonce\"\xdc\x01\n" +
	"\x10CapacityResponse\x12!\n" +
	"\fexecutor_uid\x18\x01 \x01(\tR\vexecutorUid\x12\x1a\n" +
	"\bevidence\x18\x02 \x01(\tR\bevidence\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12'\n" +
	"\x0favailable_bytes\x18\x05 \x01(\x03R\x0eavailableBytes\x12)\n" +
	"\x10available_inodes\x18\x06 \x01(\x03R\x0favailableInodes*?\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\v\n" +
	"\aRECLAIM\x10\x022\xe7\x01\n" +
	"\x04Node\x12R\n" +
	"\vGetCapacity\x12 .shiftpv.node.v1.CapacityRequest\x1a!.shiftpv.node.v1.CapacityResponse\x12D\n" +
	"\n" +
	"CreateCopy\x12\x1e.shiftpv.node.v1.EffectRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\vReclaimCopy\x12\x1e.shiftpv.node.v1.EffectRequest\x1a\x16.google.protobuf.EmptyB8Z6github.com/project-jelly/ShiftPV/src/node/rpc/protocolb\x06proto3"

var (
	file_src_node_rpc_protocol_node_proto_rawDescOnce sync.Once
	file_src_node_rpc_protocol_node_proto_rawDescData []byte
)

func file_src_node_rpc_protocol_node_proto_rawDescGZIP() []byte {
	file_src_node_rpc_protocol_node_proto_rawDescOnce.Do(func() {
		file_src_node_rpc_protocol_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_node_rpc_protocol_node_proto_rawDesc), len(file_src_node_rpc_protocol_node_proto_rawDesc)))
	})
	return file_src_node_rpc_protocol_node_proto_rawDescData
}

var file_src_node_rpc_protocol_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_node_rpc_protocol_node_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_node_rpc_protocol_node_proto_goTypes = []any{
	(Operation)(0),           // 0: shiftpv.node.v1.Operation
	(*EffectRequest)(nil),    // 1: shiftpv.node.v1.EffectRequest
	(*CapacityRequest)(nil),  // 2: shiftpv.node.v1.CapacityRequest
	(*CapacityResponse)(nil), // 3: shiftpv.node.v1.CapacityResponse
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_src_node_rpc_protocol_node_proto_depIdxs = []int32{
	2, // 0: shiftpv.node.v1.Node.GetCapacity:input_type -> shiftpv.node.v1.CapacityRequest
	1, // 1: shiftpv.node.v1.Node.CreateCopy:input_type -> shiftpv.node.v1.EffectRequest
	1, // 2: shiftpv.node.v1.Node.ReclaimCopy:input_type -> shiftpv.node.v1.EffectRequest
	3, // 3: shiftpv.node.v1.Node.GetCapacity:output_type -> shiftpv.node.v1.CapacityResponse
	4, // 4: shiftpv.node.v1.Node.CreateCopy:output_type -> google.protobuf.Empty
	4, // 5: shiftpv.node.v1.Node.ReclaimCopy:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_node_rpc_protocol_node_proto_init() }
func file_src_node_rpc_protocol_node_proto_init() {
	if File_src_node_rpc_protocol_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_node_rpc_protocol_node_proto_rawDesc), len(file_src_node_rpc_protocol_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_node_rpc_protocol_node_proto_goTypes,
		DependencyIndexes: file_src_node_rpc_protocol_node_proto_depIdxs,
		EnumInfos:         file_src_node_rpc_protocol_node_proto_enumTypes,
		MessageInfos:      file_src_node_rpc_protocol_node_proto_msgTypes,
	}.Build()
	File_src_node_rpc_protocol_node_proto = out.File
	file_src_node_rpc_protocol_node_proto_goTypes = nil
	file_src_node_rpc_protocol_node_proto_depIdxs = nil
}
